# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 28c50e81779aa1bd2138cb7ec2f36362d307d81b8a15c3eaff4d35fdc164b655cf28884fdc5360ec32ab3da4fc19619d9f851a5643c459900bc50399136efbf0

test:
  secret_key_base: 94dd1bf11e4a36a0fa9cd42dd0f92e13e2d4e995f985e6a89870eff9c2cd86208cef146849a07d4ea9b1c58adbe5c99602003bc1120dc3a9f701b9d929a38640

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
